<a href="https://colab.research.google.com/github/AhmedRafid023/deeplearning-with-tensorflow/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([1, -2, 3])

tensor_two_d = tf.constant(
    [
        [1, 2, 3],
        [2, -1, 0],
        [4, 5, 6]
    ]
)

In [ ]:
print(tensor_two_d)

tf.Tensor(
[[ 1  2  3]
 [ 2 -1  0]
 [ 4  5  6]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant(
    [
      [
        [1, 2, 3],
        [2, -1, 0],
        [4, 5, 6]
      ],

      [
        [1, 2, 3],
        [2, -1, 0],
        [4, 5, 6]
      ],
      [
        [1, 2, 3],
        [2, -1, 0],
        [4, 5, 6]
      ],
      [
        [1, 2, 3],
        [2, -1, 0],
        [4, 5, 6]
      ]
    ]
)

In [ ]:
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 2 -1  0]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 2 -1  0]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 2 -1  0]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 2 -1  0]
  [ 4  5  6]]], shape=(4, 3, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

#to print the dimension
print(tensor_three_d.ndim)

(4, 3, 3)
3


**How to convert numpy array to a tensor**

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1, 2, 4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


**Identity Tensor**

In [ ]:
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns=None,
    batch_shape=None, # here if we give the batch size 3 , we will get 3, 4x4 Matrix
    dtype=tf.dtypes.float32,
    name=None
    )
print(eye_tensor)


tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns=None,
    batch_shape=[2,4], # here if we give the batch size 3 , we will get 3, 4x4 Matrix
    dtype=tf.dtypes.float32,
    name=None
    )
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]


 [[[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]

  [[1. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 1. 0.]
   [0. 0. 0. 1.]]]], shape=(2, 4, 4, 4), dtype=float32)


**2 ta -> (4 ta -> 4x4)**

**Fill tensor**

In [ ]:
fill_tensor = tf.fill([2, 2 ,3], 1, name=None, layout=None)

In [ ]:
print(fill_tensor)

tf.Tensor(
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
zero_tensor = tf.zeros(
    [3,2],
    dtype = tf.dtypes.float32,
    name = None
)

print(zero_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


**ONE TENSOR**

In [ ]:
one_tensor =