<a href="https://colab.research.google.com/github/AhmedRafid023/deeplearning-with-tensorflow/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
tensor_one_d = tf.constant([1, -2, 3])

tensor_two_d = tf.constant(
    [
        [1, 2, 3],
        [2, -1, 0],
        [4, 5, 6]
    ]
)

In [6]:
print(tensor_two_d)

tf.Tensor(
[[ 1  2  3]
 [ 2 -1  0]
 [ 4  5  6]], shape=(3, 3), dtype=int32)


In [9]:
tensor_three_d = tf.constant(
    [
      [
        [1, 2, 3],
        [2, -1, 0],
        [4, 5, 6]
      ],

      [
        [1, 2, 3],
        [2, -1, 0],
        [4, 5, 6]
      ],
      [
        [1, 2, 3],
        [2, -1, 0],
        [4, 5, 6]
      ],
      [
        [1, 2, 3],
        [2, -1, 0],
        [4, 5, 6]
      ]
    ]
)

In [10]:
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 2 -1  0]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 2 -1  0]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 2 -1  0]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 2 -1  0]
  [ 4  5  6]]], shape=(4, 3, 3), dtype=int32)


In [14]:
print(tensor_three_d.shape)

#to print the dimension
print(tensor_three_d.ndim)

(4, 3, 3)
3
